apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-engine
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alert-engine
  template:
    metadata:
      labels:
        app: alert-engine
    spec:
      containers:
      - name: engine
        image: registry.cn-hangzhou.aliyuncs.com/stockai/alert-engine:v1.0
        env:
        - name: NATS_URL
          value: "nats://nats-cluster:4222"
        - name: CONFIG_PATH
          value: "/app/configs/prod/app.yaml"
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "500m"
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5