app:
  name: TradeRadar
  env: development

data_sources:
  tushare:
    api_key: "97aa72c0fd57dcc8cb731eccd3b0625b2ead80727aa119e984f4490b"
    base_url: "https://api.tushare.pro"
    timeout: 10s

database:
  timescaledb:
    host: localhost
    port: 5432
    user: postgres
    password: yourpassword  # 请确认这是您Docker容器中PostgreSQL的密码
    dbname: traderadar
    sslmode: disable

nats:
  url: "nats://localhost:4222"
  cluster_id: "test-cluster"  # NATS Streaming默认集群ID
  client_id: "traderadar"

api:
  port: 8080
  read_timeout: 5s
  write_timeout: 10s