app:
  name: TradeRadar
  env: development

data_sources:
  tushare:
    api_key: "97aa72c0fd57dcc8cb731eccd3b0625b2ead80727aa119e984f4490b"
    base_url: "https://api.tushare.pro"
    timeout: 10s

database:
  timescaledb:
    host: localhost
    port: 5432
    user: postgres
    password: yourpassword
    dbname: traderadar
    sslmode: disable

nats:
  url: "nats://localhost:4222"
  cluster_id: "test-cluster"
  client_id: "traderadar"

api:
  port: 8080
  read_timeout: 5s
  write_timeout: 10s

llm:
  api_url: "https://ark.cn-beijing.volces.com/api/v3/chat/completions"
  api_key: "71f7c52d-24e8-469e-8afe-8bc212c65e50"
  model_name: "doubao-1-5-pro-32k-250115"